"""crear tablas cierre de caja

Revision ID: 07382fd4f103
Revises: 02ffad261918
Create Date: 2026-09-25 00:23:17.213321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07382fd4f103'
down_revision: Union[str, None] = '02ffad261918'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cierres_caja',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('efectivo_esperado', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('efectivo_contado', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('diferencia', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('revisado_por_id', sa.Integer(), nullable=True),
    sa.Column('fecha_revision', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['revisado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fecha', name='uq_cierres_caja_fecha')
    )
    op.create_table('retiros_caja',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('motivo', sa.String(length=200), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retiros_caja_fecha'), 'retiros_caja', ['fecha'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_retiros_caja_fecha'), table_name='retiros_caja')
    op.drop_table('retiros_caja')
    op.drop_table('cierres_caja')
    # ### end Alembic commands ###
